version: '3.3'
services:
  node:
    container_name: express
    restart: always
    build: .
    ports:
      - 5000:3000
    links:
      - mongodb
    volumes:
      - .:/usr/src/app
  mongodb:
    container_name: mongoExpress
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
    volumes:
      - ./mongo_data:/data/db
